= Keymap Details

== Keyboard Shortcuts

`Alt` + `B` surrounds the selected text with asterisks (for bold/strong). Hit it once for constrained. Hit it again for unconstrained.

`Alt` + `I` surrounds the selected text with underscores (for italics/emphasis). Hit it once for constrained. Hit it again for unconstrained.

`Ctrl` + `"` surrounds the selected text (or just the cursor) with typographical double quotes.

`Ctrl` + `'` surrounds the selected text (or just the cursor) with typographical single quotes.

== Auto-Paired Punctuation

* Asterisks (strong), underscores (emphasis), backticks (monospaced), English quotation marks, and Czech quotation marks are autopaired and will wrap selected text.
    - If you start an empty pair and hit backspace, both elements are deleted.
    - If you start an empty asterisks pair and hit `Space` or `Tab`, the right element is deleted (because you probably wanted to start a list, not a strong text).

== Lists and Callouts

* At the end of a (un)ordered list item, pressing `Enter` will automatically insert the new list item "bullet."
    - Pressing `Enter` on the blank list item will remove it.
    - Pressing `Tab` on the blank list item, or selected item(s), will increase nesting level and indent it.
    - Pressing `Shift` + `Tab` on the blank list item, or selected item(s), will decrease nesting level and unindent it.
    - You can disable indentation of list items in your settings file.
* At the end of a callouts list item, pressing `Enter` will automatically insert the new list item with incremented number.
    - Pressing `Enter` on the blank list item will remove it.
